<template>
    <div class="container">
        <ServerTemplatedComponent
            :content="content"
            :components-defs="defs"
            :extract-content="extractSelector('.page-content')"
            @head="receiveHeadData"
        />
    </div>
</template>

<script>
import ServerTemplatedComponent, {
    extractSelector,
} from "~/components/ServerTemplatedComponent";
import { getOriginalPageFromRoute } from "~/utils/content";
import BlockOne from "~/components/blocks/BlockOne";
import BlockTwo from "~/components/blocks/BlockTwo";
import BlockThree from "~/components/blocks/BlockThree";

export default {
    components: { ServerTemplatedComponent },

    /**
     * Head method just copies the head data from ServerTemplatedComponent.
     * See receiveHeadData() for more explanations.
     */
    head() {
        return this.headData;
    },

    data() {
        return {
            /**
             * That content will contain the HTML of the original CMS/Wagtail
             * page. It is null here but it must be fetched during asyncData(),
             * otherwise terrors will ensue.
             */
            content: null,

            /**
             * Just exporting this function to the template so that we can use
             * it as a prop to ServerTemplatedComponent.
             */
            extractSelector,

            /**
             * Head data, used by the head() method and fueled by the head event
             * from ServerTemplatedComponent. See below for explanations.
             */
            headData: {},
        };
    },

    computed: {
        /**
         * Component definitions to be passed as a prop to
         * ServerTemplatedComponent.
         *
         * All those components are regular Vue components that however must:
         *
         * 1. Not include any <template> nor render() because this will be
         *    automatically generated by the ServerTemplatedComponent. There is
         *    no check in this so if you've defined a render function and it
         *    fails you know why.
         * 2. They MUST define a `selector` property which will allow
         *    ServerTemplatedComponent to know which parts of the HTML should be
         *    attributed to them
         *
         * Please note that you can define styles in the .vue files as usual.
         */
        defs() {
            return { BlockOne, BlockTwo, BlockThree };
        },
    },

    /**
     * Fetches (or supposedly so) data from the original page in order to have
     * the ServerTemplatedComponent compute its components.
     */
    async asyncData({ route, $axios }) {
        return {
            content: await getOriginalPageFromRoute({ route, $axios }),
        };
    },

    methods: {
        /**
         * That's with this event handler that we can receive the head content
         * in time before the HTML gets rendered on the server side. That's
         * shitty but it works.
         */
        receiveHeadData(head) {
            this.headData = head;
        },
    },
};
</script>
